spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  application:
    name: hexagonal
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
server: 
  tomcat: 
    uri-encoding: UTF-8


logging:
  level:
    ROOT: INFO
